language: ruby
dist: xenial
sudo: false
rvm:
  - 2.5.1
services:
  - postgresql
before_install:
  - gem install bundler
before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
notifications:
  email:
    recipients:
      - "mallikarjunece@gmail.com"
    on_success: "change"
    on_failure: "always"
